// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2GH3ruOm6pp20auHUpR9Rzdy5DnhVLG4',
    appId: '1:71228375420:web:aa0187581944c73d8da4f9',
    messagingSenderId: '71228375420',
    projectId: 'the-essential-fitness-app',
    authDomain: 'the-essential-fitness-app.firebaseapp.com',
    storageBucket: 'the-essential-fitness-app.firebasestorage.app',
    measurementId: 'G-0C5LDMHFBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJVdb33f-wHKcVW2x7al1p8zma4w7Hblo',
    appId: '1:71228375420:android:7650066fd60493028da4f9',
    messagingSenderId: '71228375420',
    projectId: 'the-essential-fitness-app',
    storageBucket: 'the-essential-fitness-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvIAJ8SqRXFHLiLr0k2xoL2amhXQ0lxzw',
    appId: '1:71228375420:ios:3a598db705706d3e8da4f9',
    messagingSenderId: '71228375420',
    projectId: 'the-essential-fitness-app',
    storageBucket: 'the-essential-fitness-app.firebasestorage.app',
    iosBundleId: 'com.example.theEssentialFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvIAJ8SqRXFHLiLr0k2xoL2amhXQ0lxzw',
    appId: '1:71228375420:ios:3a598db705706d3e8da4f9',
    messagingSenderId: '71228375420',
    projectId: 'the-essential-fitness-app',
    storageBucket: 'the-essential-fitness-app.firebasestorage.app',
    iosBundleId: 'com.example.theEssentialFitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2GH3ruOm6pp20auHUpR9Rzdy5DnhVLG4',
    appId: '1:71228375420:web:a851066316020ab88da4f9',
    messagingSenderId: '71228375420',
    projectId: 'the-essential-fitness-app',
    authDomain: 'the-essential-fitness-app.firebaseapp.com',
    storageBucket: 'the-essential-fitness-app.firebasestorage.app',
    measurementId: 'G-Y8DS57VXL3',
  );
}
